---
- name: Install package with pacman
  ansible.builtin.include_tasks: pacman.yaml
  when: ansible_os_family == "Archlinux"
  vars:
    ansible_become: true

- name: Install package with apt
  ansible.builtin.include_tasks: apt.yaml
  when: ansible_os_family == "Debian"
  vars:
    ansible_become: true

- name: Install package with zypper
  ansible.builtin.include_tasks: zypper.yaml
  when: ansible_os_family == "Suse"
  vars:
    ansible_become: true
