---
- name: Sync package manager repo
  community.general.pacman:
    update_cache: true

- name: Install packages
  community.general.pacman:
    name: "{{ package_manager_pacman_packages }}"
    state: present
