---
- name: Setup Workstation
  hosts: targets
  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  roles:
    - package_manager
    - oh_my_zsh
    - nvim
    - tools
    - kde
    - tmux
