---
- name: Setup Workstation
  hosts: targets
  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    user: "{{ lookup('ansible.builtin.env', 'USER') }}"
  roles:
    - package-manager
    - oh-my-zsh
    - nvim
    - tools
