---
pacman_packages:
  - yay
  - base-devel
  - git
  - neovim
  - jq
  - yq
  - fzf
  - chromium
  - plank
  - gnome-tweak-tool
  - tmux
  - zsh
  - ttf-hack-nerd
  - ttf-nerd-fonts-symbols-2048-em
  - ansible-lint
  - python-pip
  - helm
  - kubectx
  - argocd
  - ghostwriter
  - hunspell-en_US
  - flameshot

apt_packages:
  - git
  - build-essential
  - neovim
  - jq
  - fzf
  - tmux
  - zsh
  - fonts-hack-ttf
  - ansible-lint
  - python-pip
  - helm
  - unzip
