---
- name: Check existence of .oh-my-zsh
  ansible.builtin.stat:
    path: "{{ home }}/.oh-my-zsh"
  register: ohmyzsh

- name: Install oh-my-zsh
  ansible.builtin.shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not ohmyzsh.stat.exists
  register: ret
  changed_when: ret.rc != 0

- name: "Install oh-my-zsh plugins"
  block:
    - name: Check existence of powerlevel10k
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
      register: powerlevel10k
    - name: Install powerlevel10k
      ansible.builtin.git:
        repo: 'https://github.com/romkatv/powerlevel10k.git'
        dest: "{{ home }}/.oh-my-zsh/custom/themes/powerlevel10k"
        version: HEAD
      when: not powerlevel10k.stat.exists

    - name: Check existence of zsh-syntax-highlighting
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
      register: highlighting
    - name: Install zsh-syntax-highlighting
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "{{ home }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        version: HEAD
      when: not highlighting.stat.exists

    - name: Check existence of fzf-tab
      ansible.builtin.stat:
        path: "{{ home }}/.oh-my-zsh/custom/plugins/fzf-tab"
      register: fzf
    - name: Install fzf-tab
      ansible.builtin.git:
        repo: "https://github.com/Aloxaf/fzf-tab.git"
        dest: "{{ home }}/.oh-my-zsh/custom/plugins/fzf-tab"
        version: HEAD
      when: not powerlevel10k.stat.exists

- name: Copy .zshrc file
  ansible.builtin.copy:
    src: ".zshrc"
    dest: "{{ home }}/.zshrc"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /usr/bin/zsh
  become: true
