---
- name: "Install {{ item.name }} from github release"
  block:
    - name: Get latest version
      ansible.builtin.uri:
        url: "https://github.com/{{ item.user }}/{{ item.name }}/releases/latest/"
        return_content: true
        headers:
          Accept: "application/json"
      register: version

    - name: "Download {{ item.name }}"
      ansible.builtin.get_url:
        url: "https://github.com/{{ item.user }}/{{ item.name }}/releases/download/{{ version.json.tag_name }}/{{ item.name }}_{{ version.json.tag_name[1:] }}_{{ ansible_system }}_{{ item.arch }}.tar.gz"
        dest: "{{ tools_tmp_dir }}"
        mode: '0644'
      register: ret
      when: not item.lower

    - name: "Download {{ item.name }}"
      ansible.builtin.get_url:
        url: "https://github.com/{{ item.user }}/{{ item.name }}/releases/download/{{ version.json.tag_name }}/{{ item.name }}_{{ version.json.tag_name[1:] }}_{{ ansible_system | lower }}_{{ item.arch }}.tar.gz"
        dest: "{{ tools_tmp_dir }}"
        mode: '0644'
      register: ret_lower
      when: item.lower

    - name: "Extract {{ item.name }}"
      ansible.builtin.unarchive:
        src: "{{ ret.dest }}"
        dest: "{{ tools_bin_dir }}"
        include:
          - "{{ item.name }}"
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      when: not item.lower

    - name: "Extract {{ item.name }}"
      ansible.builtin.unarchive:
        src: "{{ ret_lower.dest }}"
        dest: "{{ tools_bin_dir }}"
        include:
          - "{{ item.name }}"
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"
      become: true
      when: item.lower
