---
- name: Create nvim config folder
  ansible.builtin.file:
    path: "{{ home }}/.config/nvim"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Copy init.vim
  ansible.builtin.copy:
    src: "init.vim"
    dest: "{{ home }}/.config/nvim"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0644'

- name: Create plugin manager folder
  ansible.builtin.file:
    path: "{{ home }}/.local/share/nvim/site/autoload"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: Install plugin manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{ home }}/.local/share/nvim/site/autoload"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0640'
