name: Ansible lint
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ansible lint
    steps:
      - uses: actions/checkout@v2
      - name: Run ansible-lint
        uses: ansible-community/ansible-lint-action@main
